name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Here, "original" means to use the lean-toolchain file's contents in the repository
        # Support starts at 4.23.0 because that's when the first support
        # for modules landed.
        lean-version: ["original", "v4.23.0", "v4.24.0", "v4.25.0"]
    name: CI (${{ matrix.lean-version }})

    steps:
      - uses: actions/checkout@v4

      - name: Set Lean version
        if: matrix.lean-version != 'original'
        run: echo "${{ matrix.lean-version }}" > lean-toolchain

      # uses lean standard action with all default input values
      - uses: leanprover/lean-action@v1
